version: "3"
services:
  web:
    build: .
    ports:
      - "8080:8080"
  db:
    image: "mysql"
    command: --init-file /data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - db-data:/dbData
      - ./init.sql:/data/application/init.sql
    ports:
      - "3307:3306"

volumes:
  db-data:
